name: "App Build Localtest"
description: "Builds localtest Docker images"
inputs:
  docker-profile:
    description: "Which docker profile to use"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Login to GitHub Container Registry
      if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name != 'pull_request'
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build localtest
      working-directory: src/Runtime/localtest
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
        BUILDKIT_PROGRESS: plain
        COMPOSE_FILE: 'docker-compose.yml:docker-compose.ci.yml'
      run: |
        args=""
        if [[ "${{ inputs.docker-profile }}" != "" ]]; then
          args="--profile ${{ inputs.docker-profile }}"
        fi

        if ! docker compose $args build; then
          echo "Failed to build localtest Docker images"
          exit 1
        fi
      shell: bash
