name: "My Shared Steps"
description: "Doing yarn installs with proper caching"
inputs:
  working-directory:
    description: "The directory to run yarn install in"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: 'Setting up Node'
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        cache: 'yarn'
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock
        node-version: '22'

    - name: "Getting yarn cache directory path"
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}/yarn.lock', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: 'Installing Dependencies'
      run: yarn install --immutable --inline-builds
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
        YARN_NM_MODE: 'hardlinks-local'
        HUSKY: '0'
