name: "App Build Frontend"
description: "Builds app frontend"
runs:
  using: "composite"
  steps:
    - name: Cache frontend build
      id: cache-frontend
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: src/App/frontend/dist
        key: frontend-build-${{ runner.os }}-${{ hashFiles('src/App/frontend/yarn.lock', 'src/App/frontend/package.json') }}-${{ hashFiles('src/App/frontend/src/**') }}
        restore-keys: |
          frontend-build-${{ runner.os }}-${{ hashFiles('src/App/frontend/yarn.lock', 'src/App/frontend/package.json') }}-

    - name: Installing Frontend Dependencies
      if: steps.cache-frontend.outputs.cache-hit != 'true'
      uses: ./.github/actions/yarn-install
      with:
        working-directory: src/App/frontend

    - name: Build frontend
      if: steps.cache-frontend.outputs.cache-hit != 'true'
      working-directory: src/App/frontend
      run: yarn run build
      shell: bash

    - name: Save frontend build
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: app-frontend-dist
        path: src/App/frontend/dist
        if-no-files-found: error

