apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-gateway
  labels:
    altinn.studio/otel-collector: otel-gateway
spec:
  mode: deployment
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.144.0
  serviceAccount: otel-collector
  upgradeStrategy: automatic
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          altinn.studio/otel-collector: otel-gateway
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      # Processor definitions sourced from https://github.com/dis-way/gitops-manifests/blob/1b96cf749be6e5cedfbfc09eb6caf3bd72bfb4c0/oci/otel-collector/base/collector.yaml to keep parity with existing collector behavior.
      transform/azuremonitor:
        error_mode: ignore
        trace_statements:
          - context: span
            statements:
              - set(span.attributes["http.host"], span.attributes["server.address"]) where span.attributes["server.address"] != nil
              - set(span.attributes["http.method"], span.attributes["http.request.method"]) where span.attributes["http.request.method"] != nil
              - set(span.attributes["http.scheme"], span.attributes["url.scheme"]) where span.attributes["url.scheme"] != nil
              - set(span.attributes["http.target"], span.attributes["url.path"]) where span.attributes["url.path"] != nil and (span.attributes["url.query"] == nil or span.attributes["url.query"] == "")
              - set(span.attributes["http.target"], Concat([span.attributes["url.path"], span.attributes["url.query"]], "?")) where span.attributes["url.path"] != nil and (span.attributes["url.query"] != nil and span.attributes["url.query"] != "")
              - set(span.attributes["http.url"], span.attributes["url.full"]) where span.attributes["url.full"] != nil and span.attributes["http.url"] == nil
              - set(span.attributes["http.status_code"], span.attributes["http.response.status_code"]) where span.attributes["http.response.status_code"] != nil
              - set(span.attributes["http.client_ip"], span.attributes["client.address"]) where span.attributes["client.address"] != nil
              - set(span.attributes["db.statement"], span.attributes["sql.query.text"]) where span.attributes["sql.query.text"] != nil
              - set(span.attributes["db.system"], span.attributes["db.system.name"]) where span.attributes["db.system.name"] != nil
              - set(span.attributes["http.route"], span.attributes["url.path"]) where span.attributes["url.path"] != nil and span.attributes["http.route"] == nil
              - replace_pattern(span.attributes["http.route"], "/(.*?)/(.*?)?/(.*?)?$","/$$1/$$2") where resource.attributes["k8s.deployment.name"] == "traefik" and span.attributes["http.route"] != nil
              - set(span.attributes["http.host"], resource.attributes["service.name"]) where resource.attributes["linkerd.io/proxy-deployment"] != nil
              - set(span.attributes["http.target"], resource.attributes["service.name"]) where resource.attributes["linkerd.io/proxy-deployment"] != nil
              - set(span.attributes["server.address"], resource.attributes["service.name"]) where resource.attributes["linkerd.io/proxy-deployment"] != nil
      filter/metrics_allowlist:
        error_mode: ignore
        metrics:
          include:
            match_type: regexp
            metric_names:
              - '^(altinn|http)([._].*)?$'
      cumulativetodelta/metrics:
        include:
          metric_types: [sum, histogram, exponentialhistogram]
        initial_value: auto
        # Bound in-memory state for inactive series while still covering typical scrape/export jitter.
        max_staleness: 1h
      transform/metrics_cost_control:
        error_mode: ignore
        metric_statements:
          - context: datapoint
            statements:
              - delete_key(datapoint.attributes, "client.address")
              - delete_key(resource.attributes, "client.address")
              - delete_key(datapoint.attributes, "cloud.platform")
              - delete_key(resource.attributes, "cloud.platform")
              - delete_key(datapoint.attributes, "cloud.provider")
              - delete_key(resource.attributes, "cloud.provider")
              - delete_key(datapoint.attributes, "host.id")
              - delete_key(resource.attributes, "host.id")
              - delete_key(datapoint.attributes, "host.name")
              - delete_key(resource.attributes, "host.name")
              - delete_key(datapoint.attributes, "http.url")
              - delete_key(resource.attributes, "http.url")
              - delete_key(datapoint.attributes, "k8s.container.name")
              - delete_key(resource.attributes, "k8s.container.name")
              - delete_key(datapoint.attributes, "k8s.pod.ip")
              - delete_key(resource.attributes, "k8s.pod.ip")
              - delete_key(datapoint.attributes, "k8s.pod.name")
              - delete_key(resource.attributes, "k8s.pod.name")
              - delete_key(datapoint.attributes, "k8s.pod.uid")
              - delete_key(resource.attributes, "k8s.pod.uid")
              - delete_key(datapoint.attributes, "k8s.node.name")
              - delete_key(resource.attributes, "k8s.node.name")
              - delete_key(datapoint.attributes, "network.local.address")
              - delete_key(resource.attributes, "network.local.address")
              - delete_key(datapoint.attributes, "network.local.port")
              - delete_key(resource.attributes, "network.local.port")
              - delete_key(datapoint.attributes, "network.peer.address")
              - delete_key(resource.attributes, "network.peer.address")
              - delete_key(datapoint.attributes, "network.peer.port")
              - delete_key(resource.attributes, "network.peer.port")
              - delete_key(datapoint.attributes, "process.pid")
              - delete_key(resource.attributes, "process.pid")
              - delete_key(datapoint.attributes, "server.address")
              - delete_key(resource.attributes, "server.address")
              - delete_key(datapoint.attributes, "server.port")
              - delete_key(resource.attributes, "server.port")
              - delete_key(datapoint.attributes, "service.instance.id")
              - delete_key(resource.attributes, "service.instance.id")
              - delete_key(datapoint.attributes, "url.full")
              - delete_key(resource.attributes, "url.full")
              - delete_key(datapoint.attributes, "url.scheme")
              - delete_key(resource.attributes, "url.scheme")
              - delete_key(datapoint.attributes, "user_agent.original")
              - delete_key(resource.attributes, "user_agent.original")
      tail_sampling:
        decision_wait: 40s
        num_traces: 50000
        decision_cache:
          # Keep sampled decisions longer than in-memory traces to include late spans.
          sampled_cache_size: 100000
        policies:
          - name: always-sample-attr
            type: string_attribute
            string_attribute:
              key: altinn.studio.sampling
              values: [always]
          - name: errors
            type: status_code
            status_code:
              status_codes: [ERROR]
          - name: slow-traces
            type: latency
            latency:
              threshold_ms: 1000
          - name: kubernetes-wrapper-probabilistic
            type: and
            and:
              and_sub_policy:
                - name: is-kubernetes-wrapper
                  type: string_attribute
                  string_attribute:
                    key: service.name
                    values: [kubernetes-wrapper]
                - name: low-rate
                  type: probabilistic
                  probabilistic:
                    sampling_percentage: 1
          - name: probabilistic
            type: and
            and:
              and_sub_policy:
                - name: not-kubernetes-wrapper
                  type: string_attribute
                  string_attribute:
                    key: service.name
                    values: [kubernetes-wrapper]
                    invert_match: true
                - name: default-rate
                  type: probabilistic
                  probabilistic:
                    sampling_percentage: 10
      batch:
        send_batch_size: 1024
        timeout: 5s
